Kapasitematik/Controllers/YorumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kapasitematik.Database;
using Microsoft.AspNetCore.Http;
using Kapasitematik.Models;

namespace Kapasitematik.Controllers
{
    [ControlLogin]
    public class YorumController : Controller
    {
        private readonly KpstmtkSiteContext _context;

        public YorumController(KpstmtkSiteContext context)
        {
            _context = context;
        }

        // GET: Yorum
        [Route("yorum")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Name = HttpContext.Session.GetString("FirstName");
            ViewBag.YorumOnay = _context.Yorum.Where(x => x.Onay == false).Count();
            var kpstmtkSiteContext = _context.Yorum.Include(y => y.FkArticle);
            return View(await kpstmtkSiteContext.ToListAsync());
        }

        // GET: Yorum/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yorum = await _context.Yorum
                .Include(y => y.FkArticle)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (yorum == null)
            {
                return NotFound();
            }

            return View(yorum);
        }

        // GET: Yorum/Create
        public IActionResult Create()
        {
            ViewBag.Name = HttpContext.Session.GetString("FirstName");
            ViewBag.YorumOnay = _context.Yorum.Where(x => x.Onay == false).Count();
            ViewData["FkArticleId"] = new SelectList(_context.Article, "Id", "Baslik");
            return View();
        }

        // POST: Yorum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Icerik,AdSoyad,Eposta,Onay,FkUserId,FkArticleId")] Yorum yorum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(yorum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["mesaj"] = "Hata oluştu! Tekrar Deneyiniz.";// mesaj TempData içerisinde saklanır
            }
            ViewData["FkArticleId"] = new SelectList(_context.Article, "Id", "Baslik", yorum.FkArticleId);
            return View(yorum);
        }

        // GET: Yorum/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Name = HttpContext.Session.GetString("FirstName");
            ViewBag.YorumOnay = _context.Yorum.Where(x => x.Onay == false).Count();
            if (id == null)
            {
                return NotFound();
            }

            var yorum = await _context.Yorum.FindAsync(id);
            if (yorum == null)
            {
                return NotFound();
            }
            ViewData["FkArticleId"] = new SelectList(_context.Article, "Id", "Baslik", yorum.FkArticleId);
            return View(yorum);
        }

        // POST: Yorum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Icerik,AdSoyad,Eposta,Onay,FkUserId,FkArticleId")] Yorum yorum)
        {
            if (id != yorum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(yorum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!YorumExists(yorum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        //throw;
                        TempData["mesaj"] = "Hata oluştu! Tekrar Deneyiniz.";// mesaj TempData içerisinde saklanır
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["mesaj"] = "Hata oluştu! Tekrar Deneyiniz.";// mesaj TempData içerisinde saklanır
            }
            ViewData["FkArticleId"] = new SelectList(_context.Article, "Id", "Baslik", yorum.FkArticleId);
            return View(yorum);
        }

        public IActionResult DeleteYorum(int id)
        {
            var blog = _context.Yorum.Find(id);
            _context.Yorum.Remove(blog);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool YorumExists(int id)
        {
            return _context.Yorum.Any(e => e.Id == id);
        }
    }
}

Kapasitematik/Views/Yorum/Create.cshtml
@model Kapasitematik.Database.Yorum

@{
    ViewData["Title"] = "Yorum Ekle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<h2>Yorum Ekle</h2>*@

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" asp-controller="Yorum" asp-action="Create" novalidate="novalidate">
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">İçerik <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="text" asp-for="Icerik">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Ad Soyad <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="text" asp-for="AdSoyad">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Eposta <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="email" asp-for="Eposta">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Onay <span class="required">*</span></label>
            <div class="col-lg-10">
                <input type="checkbox" asp-for="Onay">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Makale Başlığı <span class="required">*</span></label>
            <div class="col-lg-10">
                <select asp-for="FkArticleId" class="form-control" asp-items="ViewBag.FkArticleId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Ekle</button>
                <button class="btn btn-default" type="button"><a href="/yorum">İptal</a></button>
            </div>
        </div>
    </form>


    @if (TempData["mesaj"] != null)
    {
        <div id="dialog" title="Bilgi Mesajı">
            <p>
                @TempData["mesaj"].ToString()
            </p>
        </div>
    }
</div>
@section Scripts {
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.0/jquery-ui.js"></script>
    <script>
        $("#dialog").dialog();
    </script>
}

Kapasitematik/Views/Yorum/Edit.cshtml
@model Kapasitematik.Database.Yorum

@{
    ViewData["Title"] = "Yorum Düzenle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<h2>Yorum Düzenle</h2>*@

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" asp-controller="Yorum" asp-action="Edit" novalidate="novalidate">
        <div class="form-group ">
            <label for="cname" class="control-label col-lg-2" hidden>Id <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" asp-for="Id" minlength="5" type="hidden" required="">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">İçerik <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="text" asp-for="Icerik">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Ad Soyad <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="text" asp-for="AdSoyad">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Eposta <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" type="email" asp-for="Eposta">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Onay <span class="required">*</span></label>
            <div class="col-lg-10">
                <input type="checkbox" asp-for="Onay">
            </div>
        </div>
        <div class="form-group ">
            <label for="cemail" class="control-label col-lg-2">Makale Başlığı <span class="required">*</span></label>
            <div class="col-lg-10">
                <select asp-for="FkArticleId" class="form-control" asp-items="ViewBag.FkArticleId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Düzenle</button>
                <button class="btn btn-default" type="button"><a href="/yorum">İptal</a></button>
            </div>
        </div>
    </form>

    @if (TempData["mesaj"] != null)
    {
        <div id="dialog" title="Bilgi Mesajı">
            <p>
                @TempData["mesaj"].ToString()
            </p>
        </div>
    }
</div>
@section Scripts {
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.0/jquery-ui.js"></script>
    <script>
        $("#dialog").dialog();
    </script>
}

Kapasitematik/Views/Yorum/Index.cshtml
@model IEnumerable<Kapasitematik.Database.Yorum>

@{
    ViewData["Title"] = "Yorum Listesi";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link href="/DataTables-1.10.21/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css" rel="stylesheet" />
<link href="/NiceAdmin/css/font-awesome.css" rel="stylesheet" />

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Yorum Listesi
            </header>
            <table border="0" cellspacing="5" cellpadding="5">
                <tbody>
                    <tr>
                        <td><a href="/Yorum/Create" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> Yeni Yorum</a></td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-striped table-advance table-hover" id="mapTable">
                <thead>
                    <tr>
                        <th><i class="fa fa-globe"></i> İçerik</th>
                        <th><i class="fa fa-compass"></i> Adı Soyadı</th>
                        <th><i class="fa fa-compass"></i> Eposta</th>
                        <th><i class="fa fa-info"></i> Onay</th>
                        <th><i class="fa fa-header"></i> Makale Başlığı</th>
                        <th><i class="fa fa-pencil"></i> Güncelle</th>
                        <th><i class="fa fa-trash"></i> Sil</th>
                    </tr>
                </thead>
                <tbody id="tblIcerik">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Icerik)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AdSoyad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Eposta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Onay)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FkArticle.Baslik)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Düzenle</a>
                            </td>
                            <td>
                                <a class="btn btn-danger" asp-action="DeleteYorum" asp-route-id="@item.Id">Sil</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @*<button type="button" id="export" class="btn btn-primary"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Excel'e Aktar</button>*@
        </section>
    </div>
</div>
@section Scripts{
    <script src="/DataTables-1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="/DataTables-1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {           
            $("#mapTable").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Turkish.json"
                }
            });
        });
    </script>
}